name: Update Electoral Map

on:
  schedule:
    - cron: '0 6 * * *'  # Runs at 6:00 UTC every day
  workflow_dispatch:      # Allows manual triggering

jobs:
  update_map:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas geopandas matplotlib numpy
      
      - name: Run map generation script
        run: |
          python generate_map.py
      
      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'github-actions@github.com'
          git add -A docs/
          git diff --quiet && git diff --staged --quiet || git commit -m "Update electoral map (automated)"
          git push